export const ACTION_START = "ACTION_START";
export const ACTION_FAILED = "ACTION_FAILED";
export const ACTION_SUCCESS = "ACTION_SUCCESS";
export const ACTION_CLEAR = "ACTION_CLEAR";

export const CLEAR_MOVIE_SUCCESS = "CLEAR_MOVIE_SUCCESS";
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";
export const GET_PEOPLE_SUCCESS = "GET_PEOPLE_SUCCESS";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
